# tutorial taken from: 
# https://oneuptime.com/blog/post/2026-01-25-monitor-docker-prometheus/view

global:
  scrape_interval: 7s
  evaluation_interval: 7s
  # what's the difference between these two?
  # scrape_interval: how often Prometheus scrapes the targets for metrics
  # evaluation_interval: how often Prometheus evaluates the rules (if you have any alerting or recording rules defined)

scrape_configs:
  # Scrape docker-exporter for all the container metrics
  - job_name: 'docker-exporter'
    static_configs:
      - targets: ['docker-exporter:8000']

  # Scrape the Flask application metrics exposed at /metrics.
  - job_name: 'flask-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['flask-app:8080']

  # Scrape Prometheus itself - why? isn't it included in the container metrics?
 # - job_name: 'prometheus'
 #   static_configs:
 #     - targets: ['localhost:9090']


  # daemon metrics
  # - job_name: 'docker'
  #   static_configs:
  #    - targets: ['localhost:9323']
